mapping={'How to set up my data in the UdyogYantra system?': 'basics',
 'How to log into the UdyogYantra platform?': 'Login Process',
 'How to manage brands in the system?': 'Brand Management',
 'How to create a new brand?': 'Brand Management',
 'How to view existing brands?': 'Brand Management',
 'How to update brand information?': 'Brand Management',
 'How to delete a brand?': 'Brand Management',
 'How to manage stores in the UdyogYantra system?': 'Store Management',
 'How to create a new store?': 'Store Management',
 'How to view the list of stores?': 'Store Management',
 'How to update store information?': 'Store Management',
 'How to delete a store?': 'Store Management',
 'How to manage product categories in the UdyogYantra system?': 'Product Category Management',
 'How to create a new product category?': 'Product Category Management',
 'How to view product categories?': 'Product Category Management',
 'How to update product category information?': 'Product Category Management',
 'How to delete a product category?': 'Product Category Management',
 'How to manage product subcategories in the UdyogYantra system?': 'Product Subcategory Management',
 'How to create a new product subcategory?': 'Product Subcategory Management',
 'How to view product subcategories?': 'Product Subcategory Management',
 'How to delete a product subcategory?': 'Product Subcategory Management',
 'How to manage products in the UdyogYantra system?': 'Product Management',
 'How to create a new product?': 'Product Management',
 'How to view existing products?': 'Product Management',
 'How to update product information?': 'Product Management',
 'How to enable or disable a product?': 'Product Management',
 'How to delete a product?': 'Product Management',
 'How to manage product variants in the UdyogYantra system?': 'Product Variant Management',
 'How to create product variants?': 'Product Variant Management',
 'How to view product variants?': 'Product Variant Management',
 'How to update product variant details?': 'Product Variant Management',
 'How to delete a product variant?': 'Product Variant Management',
 'How to manage recipes in the UdyogYantra system?': 'Recipe Management',
 'How to create a new recipe?': 'Recipe Management',
 'How to view existing recipes?': 'Recipe Management',
 'How to update recipe information?': 'Recipe Management',
 'How to delete a recipe?': 'Recipe Management',
 'How to upload data in the UdyogYantra system?': 'Upload Data',
 'How to prepare a data file for uploading?': 'Upload Data',
 'How to ensure proper mapping of data fields during upload?': 'Upload Data',
 'How to monitor upload status in the UdyogYantra system?': 'Upload Data',
 'How to create a production plan?': 'basics',
 'How to generate a sales order to the base kitchen?': 'basics',
 'How to initiate a facility management system (FMS) order?': 'basics',
 'How to create a warehouse indent?': 'basics',
 'How to receive vendor deliveries?': 'basics',
 'How to manage raw material receiving in the kitchen?': 'basics',
 'How to implement a machine scanning process?': 'basics',
 'How to facilitate internal stock transfer?': 'basics',
 'How to conduct audits in the UdyogYantra system?': 'basics',
 'How to analyze data collected in the system?': 'basics',
 'How to monitor and manage assets in the UdyogYantra system?': 'basics',
 'How to generate vendor orders?': 'basics',
 'How to manage inventory effectively in the UdyogYantra system?': 'basics',
 'How to ensure compliance with standard operating procedures (SOPs) through the UdyogYantra platform?': 'basics',
 'tell me about the company UdyogYantra?': 'basics'}

intents=['Login Process',
 'Brand Management',
 'Store Management',
 'Product Category Management',
 'Product Subcategory Management',
 'Product Management',
 'Product Variant Management',
 'Recipe Management',
 'Upload Data',
"basics"]

# i2p={
#     intent[9]:pages[:6]+pages[40:],
#     intent[0]:pages[6],
#     intent[1]:pages[6:11],
#     intent[2]:pages[11:19],
#     intent[3]:pages[19:23],
#     intent[4]:pages[23:25],
#     intent[5]:pages[25:31],
#     intent[6]:pages[30:33],
#     intent[7]:pages[33:37],
#     intent[8]:pages[36:40]
# }

url_map={
    'Login Process':"https://bakingo.resoee.com/console2/login",
    'Brand create':"https://bakingo.resoee.com/console2/brands/new",
    'Brand update':"https://bakingo.resoee.com/console2/brands",
    'Brand delete':"https://bakingo.resoee.com/console2/brands",
    'Brand view':"https://bakingo.resoee.com/console2/brands",
    'Brand enable':"https://bakingo.resoee.com/console2/brands",
    'Brand disable':"https://bakingo.resoee.com/console2/brands",
    'Brand modify':"https://bakingo.resoee.com/console2/brands",
    'Stores create':"https://bakingo.resoee.com/console2/outlets/stores/new",
    'Stores update':"https://bakingo.resoee.com/console2/outlets/stores",
    'Stores delete':"https://bakingo.resoee.com/console2/outlets/stores",
    'Stores view':"https://bakingo.resoee.com/console2/outlets/stores",
    'Stores enable':"https://bakingo.resoee.com/console2/outlets/stores",
    'Stores disable':"https://bakingo.resoee.com/console2/outlets/stores",
    'Stores modify':"https://bakingo.resoee.com/console2/outlets/stores",
    'Product create':"https://bakingo.resoee.com/console2/products/all/new",
    'Product update':"https://bakingo.resoee.com/console2/products/all",
    'Product delete':"https://bakingo.resoee.com/console2/products/all",
    'Product view':"https://bakingo.resoee.com/console2/products/all",
    'Product enable':"https://bakingo.resoee.com/console2/products/all",
    'Product disable':"https://bakingo.resoee.com/console2/products/all",
    'Product modify':"https://bakingo.resoee.com/console2/products/all",
    'Product Category create':"https://bakingo.resoee.com/console2/products/category/new",
    'Product Category update':"https://bakingo.resoee.com/console2/products/category",
    'Product Category delete':"https://bakingo.resoee.com/console2/products/category",
    'Product Category view':"https://bakingo.resoee.com/console2/products/category",
    'Product Category enable':"https://bakingo.resoee.com/console2/products/category",
    'Product Category disable':"https://bakingo.resoee.com/console2/products/category",
    'Product Category modify':"https://bakingo.resoee.com/console2/products/category",
    'Product Subcategory create':"https://bakingo.resoee.com/console2/products/sub/category/new",
    'Product Subcategory update':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Subcategory delete':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Subcategory view':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Subcategory enable':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Subcategory disable':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Subcategory modify':"https://bakingo.resoee.com/console2/products/sub/category",
    'Product Variant create':"https://bakingo.resoee.com/console2/products/threshold/variants/new",
    'Product Variant update':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Product Variant delete':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Product Variant view':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Product Variant enable':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Product Variant disable':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Product Variant modify':"https://bakingo.resoee.com/console2/products/threshold/variants",
    'Recipe create':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe/new",
    'Recipe update':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Recipe delete':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Recipe view':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Recipe enable':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Recipe disable':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Recipe modify':"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    'Upload Data':"https://bakingo.resoee.com/console2/upload/template",
    "basics":None
}

url_mapping={
    "Dashboard":"https://bakingo.resoee.com/console2/dashboard",
    "Ops Dashboard":"https://bakingo.resoee.com/console2/dashboard",
    "AI Dashboard":"https://bakingo.resoee.com/console2/ai-dashboard",
    "Stock Dashboard":"https://bakingo.resoee.com/console2/asset-dashboard",
    "Process Flow":"https://bakingo.resoee.com/console2/process-flow",
    "Product Traceability":"https://bakingo.resoee.com/console2/order/tracking",
    "My Users Access":"https://bakingo.resoee.com/console2/account/access/user",
    "Modules Configuration":"https://bakingo.resoee.com/console2/account/modules/confriguration",
    "My Licenses":"https://bakingo.resoee.com/console2/account/my-licenses",
    "Wastage Reasons":"https://bakingo.resoee.com/console2/account/wastage/reasons",
    "My Audits":"https://bakingo.resoee.com/console2/account/my-audits",
    "My Machines":"https://bakingo.resoee.com/console2/account/my-machines",
    "My Containers":"https://bakingo.resoee.com/console2/account/my-containers",
    "Process Config":"https://bakingo.resoee.com/console2/process-config",
    "Subscriptions History":"https://bakingo.resoee.com/console2/analytics/my-subscriptions/history?clear=true",
    "AI Accuracies":"https://bakingo.resoee.com/console2/ai-workflow/accuracies",
    "AI Model Creation":"https://bakingo.resoee.com/console2/ai-workflow/ai-model",
    "Asset Types":"https://bakingo.resoee.com/console2/asset/asset-category",
    "Asset Monitoring":"https://bakingo.resoee.com/console2/asset/asset-monitoring",
    "Immovable Asset":"https://bakingo.resoee.com/console2/asset/asset-immovable",
    "Packaging Capacity":"https://bakingo.resoee.com/console2/asset/capacity",
    "My Franchise":"https://bakingo.resoee.com/console2/analytics/my-franchisee",
    "Request Refunds":"https://bakingo.resoee.com/console2/refunds/request",
    "Approve Refunds":"https://bakingo.resoee.com/console2/refunds/approve",
    "Refunds History":"https://bakingo.resoee.com/console2/refunds/history",
    "Temperature Images":"https://bakingo.resoee.com/console2/analytics/temperature/images",
    "Bills":"https://bakingo.resoee.com/console2/analytics/po/bill",
    "Bills Summary":"https://bakingo.resoee.com/console2/analytics/po/vendor/bills/summary",
    "Payment made":"https://bakingo.resoee.com/console2/analytics/po/payment/made",
    "Debit/Credit Note":"https://bakingo.resoee.com/console2/analytics/po/credits",
    "Ad-Hoc Expense/Income":"https://bakingo.resoee.com/console2/financial/petty",
    "Utilities":"https://bakingo.resoee.com/console2/financial/utilities",
    "Upload Data":"https://bakingo.resoee.com/console2/upload/template",
    "Generate E-Way Bill":"https://bakingo.resoee.com/console2/analytics/po/EWayBill/generate",
    "Create Order":"https://bakingo.resoee.com/console2/analytics/po/create",
    "Internal Store Sale Orders":"https://bakingo.resoee.com/console2/analytics/inventory/list/po",
    "Delivery Challan":"https://bakingo.resoee.com/console2/analytics/po/delivery/challan",
    "Vendor Orders":"https://bakingo.resoee.com/console2/analytics/list/vendor/orders",
    "Asset Purchase Order":"https://bakingo.resoee.com/console2/analytics/list/capex/vendor/orders",
    "GRN Listing":"https://bakingo.resoee.com/console2/analytics/list/grn",
    "Assets Quote":"https://bakingo.resoee.com/console2/analytics/list/quote",
    "Internal Purchase Orders":"https://bakingo.resoee.com/console2/analytics/internal/po/list",
    "Asset Transfer Order":"https://bakingo.resoee.com/console2/analytics/list/asset/store",
    "Store Bills":"https://bakingo.resoee.com/console2/analytics/po/internal/bill",
    "Orders History":"https://bakingo.resoee.com/console2/analytics/order/history/list",
    "Buyers Sales Orders":"https://bakingo.resoee.com/console2/analytics/list/buyer/orders",
    "FMS Orders List":"https://bakingo.resoee.com/console2/analytics/list/fms",
    "Production Plans":"https://bakingo.resoee.com/console2/analytics/productionPlans",
    "Indent List":"https://bakingo.resoee.com/console2/analytics/inventory/list/indent",
    "Custom Reports":"https://bakingo.resoee.com/console2/inventory-reports",
    "COGS History":"https://bakingo.resoee.com/console2/analytics/cogs/history/list?clear=true",
    "Product Cost Analysis":"https://bakingo.resoee.com/console2/analytics/bom/summary",
    "Production Cost History":"https://bakingo.resoee.com/console2/analytics/bom/history/list?clear=true",
    "Inventory Analysis":"https://bakingo.resoee.com/console2/analytics/stock/summary",
    "Inventory Analysis History":"https://bakingo.resoee.com/console2/analytics/stock/history/list?clear=true",
    "Day End Report":"https://bakingo.resoee.com/console2/dayendreport",
    "Transit Loss Analysis":"https://bakingo.resoee.com/console2/analytics/transit/summary",
    "Transit Loss Analysis History":"https://bakingo.resoee.com/console2/analytics/transit/history/list?clear=true",
    "Forecasting Analysis":"https://bakingo.resoee.com/console2/analytics/forecasting/summary",
    "Forecasting Analysis List":"https://bakingo.resoee.com/console2/analytics/forecasting/analysis/list",
    "Variance Analysis":"https://bakingo.resoee.com/console2/analytics/audit/summary",
    "Variance History":"https://bakingo.resoee.com/console2/analytics/audit/history/list?clear=true",
    "AI GRN History":"https://bakingo.resoee.com/console2/analytics/ai/grn/history",
    "AI GRN Images":"https://bakingo.resoee.com/console2/analytics/ai/grn/images",
    "Stock Consumption":"https://bakingo.resoee.com/console2/analytics/inventory/consumption/stock",
    "Cooking History":"https://bakingo.resoee.com/console2/analytics/cooking/analysis/list?",
    "Ingredients Images":"https://bakingo.resoee.com/console2/analytics/cooking/images",
    "Production History":"https://bakingo.resoee.com/console2/analytics/production/history",
    "Production Images":"https://bakingo.resoee.com/console2/analytics/production/images",
    "Wastage History":"https://bakingo.resoee.com/console2/analytics/wastage/history/list?clear=true",
    "Wastage Images":"https://bakingo.resoee.com/console2/analytics/wastage/images",
    "Wastage Components":"https://bakingo.resoee.com/console2/analytics/wastage/components",
    "Quality Analysis":"https://bakingo.resoee.com/console2/analytics/quality/analysis?clear=true",
    "Quality History":"https://bakingo.resoee.com/console2/analytics/quality/history/list?clear=true",
    "Nutrition Analysis":"https://bakingo.resoee.com/console2/analytics/quality/nutrition",
    "Current Stock":"https://bakingo.resoee.com/console2/analytics/inventory/sku-report",
    "Stock History":"https://bakingo.resoee.com/console2/analytics/inventory/stock",
    "Inventory Summary":"https://bakingo.resoee.com/console2/analytics/inventory/summary",
    "Inventory Analysis":"https://bakingo.resoee.com/console2/analytics/inventory/analysis?clear=true",
    "AI Filling/Packaging Summary":"https://bakingo.resoee.com/console2/ai_packaging",
    "AI Filling/Packaging History":"https://bakingo.resoee.com/console2/analytics/cooking/analysis/list?",
    "AI Dispatch History":"https://bakingo.resoee.com/console2/analytics/ai/dispatch/history",
    "AI Dispatch Images":"https://bakingo.resoee.com/console2/analytics/ai/dispatch/images",
    "Brand Trends":"https://bakingo.resoee.com/console2/analytics/brand-trends",
    "Orders History":"https://bakingo.resoee.com/console2/analytics/brand-trends",
    "Feature Images":"https://bakingo.resoee.com/console2/analytics/feature/images",
    "Temperature Digit Images":"https://bakingo.resoee.com/console2/analytics/temperature/digit/images",
    "App Outwarding Images":"https://bakingo.resoee.com/console2/analytics/app/outwarding/images",
    "My Customers":"https://bakingo.resoee.com/console2/analytics/my-customers",
    "Store Settings":"https://bakingo.resoee.com/console2/outlets/settings",
    "Stores":"https://bakingo.resoee.com/console2/outlets/stores",
    "Riders":"https://bakingo.resoee.com/console2/outlets/riders",
    "Printer Config":"https://bakingo.resoee.com/console2/outlets/printer-config",
    "Live View":"https://bakingo.resoee.com/console2/outlets/live",
    "Holiday":"https://bakingo.resoee.com/console2/outlets/holiday",
    "My Brands":"https://bakingo.resoee.com/console2/brands",
    "Active Products":"https://bakingo.resoee.com/console2/products/active",
    "All Products":"https://bakingo.resoee.com/console2/products/all",
    "Customization":"https://bakingo.resoee.com/console2/products/customizations",
    "Variants":"https://bakingo.resoee.com/console2/products/threshold/variants",
    "Product Category":"https://bakingo.resoee.com/console2/products/category",
    "Product Sub-Category":"https://bakingo.resoee.com/console2/products/sub/category",
    "Combos":"https://bakingo.resoee.com/console2/products/combos",
    "Nutritional info":"https://bakingo.resoee.com/console2/products/nutritional-info",
    "Bulk Ordering":"https://bakingo.resoee.com/console2/products/bulk",
    "Subscription":"https://bakingo.resoee.com/console2/products/subscription",
    "Master Menu":"https://bakingo.resoee.com/console2/menus/master",
    "Quality Settings":"https://bakingo.resoee.com/console2/kitchen/quality/setting",
    "Quality Config":"https://bakingo.resoee.com/console2/kitchen/quality/config",
    "Live QC":"https://bakingo.resoee.com/console2/kitchen/quality/live",
    "Cooking Settings":"https://bakingo.resoee.com/console2/kitchen/cooking/setting",
    "Recipe":"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    "Cooking Config":"https://bakingo.resoee.com/console2/kitchen/cooking/recipe",
    "Inventory Config":"https://bakingo.resoee.com/console2/kitchen/inventory/config",
    "Vendors List":"https://bakingo.resoee.com/console2/vendors",
    "Vendor Contract":"https://bakingo.resoee.com/console2/vendor/contract",
    "Buyers List":"https://bakingo.resoee.com/console2/buyers",
    "Buyers Contract":"https://bakingo.resoee.com/console2/buyer/contract",
    "Product Mapping":"https://bakingo.resoee.com/console2/product-process-map",
    "Features":"https://bakingo.resoee.com/console2/kitchen/features",
    "Left Over Inventory List":"https://bakingo.resoee.com/console2/left-over-inventory/process",
    "Left Over Inventory History Scans":"https://bakingo.resoee.com/console2/left-over-inventory/history",
    "Wastage Inventory":"https://bakingo.resoee.com/console2/wastage",
    "Similar Products Mapping":"https://bakingo.resoee.com/console2/similar-products-mapping",
    "Regions Mapping":"https://bakingo.resoee.com/console2/regions-mapping",
    "Label Generator":"https://bakingo.resoee.com/console2/label/generator/list",
    "Shift Management":"https://bakingo.resoee.com/console2/label/generator/list"
}
